4941 - Голощапов Дмитрий Алексеевич
suaicloud/docker-app pull request #9
Opened 2022-12-12 19:21 UTC by GimazDo

2022-12-12 21:18 UTC, Dimique requested changes

2022-12-12 21:18 UTC, Dimique commented on src/Dockerfile
> +CMD  uvicorn main:app --host 0.0.0.0 --port ${APP_PORT}
кажется, для CMD нужно передавать аргументы списком

2022-12-18 20:00 UTC, Dimique approved these changes

2022-12-18 20:04 UTC, 1k1ru commented
Принято

2022-12-18 20:04 UTC, closed without merging